logging:
  level: DEBUG
  format: '%(asctime)s %(levelname)-5s [%(process)d-%(thread)d-%(threadName)s] %(module)s#%(funcName)s : %(message)s'
  filename: ./logs/app.log
database:
  url: mysql+pymysql://username:password@localhost:3306/rpa
redis:
  host: localhost
  port: 6379
  password: password
